# 1. Install Dependencies

In [ ]:
!pip install stable-baselines[extra]

In [3]:
# Import Gym stuff

import gym 
from gym import Env # the superclass to create our own environment
from gym.spaces import Discrete, Box, Dict, Tuple, MultiBinary, MultiDiscrete # all spaces in OpenAI gym

# Import helpers
import numpy as np
import random
import os

# Import Stable Baselines stuff
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy

# 2. Types of Spaces

### 2.1.1 Discrete(n) -> an integer in this range: [0,n)

In [8]:
Discrete(3).sample()

2

### 2.1.2 Box(low, high, shape)

In [14]:
Box(0,1,shape=(3,3)).sample() # low value, high value, shape of box, list of lists

array([[0.41953257, 0.06215569, 0.7592652 ],
       [0.68332195, 0.76335454, 0.3091818 ],
       [0.72569877, 0.5437112 , 0.7241394 ]], dtype=float32)

In [15]:
Box(0,1,shape=(3,)).sample() # low value, high value, shape of box, list of lists

array([0.40188432, 0.4996985 , 0.18260233], dtype=float32)

### 2.1.3 MultiBinary(n) -> a binary list size n

In [68]:
MultiBinary(4).sample()

array([0, 1, 0, 0], dtype=int8)

### 2.1.4 MultiDiscrete([list]) -> list of discrete values from 0-index_value

In [80]:
MultiDiscrete([5,2,2]).sample()

array([3, 1, 0])

---

### 2.2.1 Wrapper Space Tuple

In [17]:
Tuple((Discrete(3), Box(0,1,shape=(3,)))).sample()

(0, array([0.5012581 , 0.6039192 , 0.21475749], dtype=float32))

### 2.2.2 Wrapper Space Dict

In [42]:
Dict({'height':Discrete(2), 'speed':Box(0,100,shape=(1,))}).sample()

OrderedDict([('height', 0), ('speed', array([10.212136], dtype=float32))])

# 3. Building an environment

In [84]:
height = 10
width = 10
Box(0, 255, [height, width, 3]).sample()

array([[[ 43.737316 , 155.54675  , 245.06679  ],
        [ 10.0939045, 203.284    , 111.23647  ],
        [171.26271  ,  87.62479  ,  31.534622 ],
        [ 69.20448  ,  74.20101  ,  52.334316 ],
        [ 63.22423  ,  47.51977  , 214.14557  ],
        [202.06992  , 168.43617  , 200.65025  ],
        [161.11113  , 162.69044  , 129.39917  ],
        [ 41.295338 , 216.3721   ,  62.58159  ],
        [242.01915  , 159.84242  , 124.22362  ],
        [164.67651  , 128.56833  ,  88.76878  ]],

       [[181.11075  , 174.29988  ,  74.13048  ],
        [ 75.61644  ,  75.604    , 123.48941  ],
        [254.75487  , 136.55449  , 159.0055   ],
        [ 43.065838 ,  88.65428  , 183.9955   ],
        [ 54.056934 , 161.99127  , 103.738304 ],
        [ 27.556282 , 167.58179  , 121.10621  ],
        [120.59809  ,  31.775696 , 249.1367   ],
        [149.30173  , 144.97403  , 179.73125  ],
        [112.62136  , 159.41138  , 178.8009   ],
        [ 17.917181 ,  55.535873 , 176.50002  ]],

       [[104.063

# 4. etcetc